const {chromium}=require('/work/node_modules/playwright');const assert=require('node:assert/strict');const fs=require('node:fs'),http=require('node:http');
let notes=Array.from({length:13},(_,i)=>({id:i+1,title:['Window delivery confirmation','Kitchen layout approved','Prepare floor inspection'][i%3],content:'<p>Review the latest project documents before the next site meeting.</p>',visibility:'public',noteType:i%2?'decision':'general',userId:'emma',updatedAt:'2026-09-19T09:00:00Z'}));
const server=http.createServer(async(req,res)=>{const url=new URL(req.url,'http://localhost');let body;
if(url.pathname.endsWith('/notes/list')){const matches=notes.filter(n=>n.visibility===url.searchParams.get('visibility')&&(!url.searchParams.get('noteType')||n.noteType===url.searchParams.get('noteType')));const start=(Number(url.searchParams.get('page'))-1)*12;body={notes:matches.slice(start,start+12),total:matches.length,private_available:true}}
else if(url.pathname.endsWith('/direct-chats'))body=[];
else if(url.pathname.endsWith('/card-comments'))body={comments:[{id:1,actorId:'thomas',actorDisplayName:'Thomas Jansen',message:'Please review the drawings.',createdAt:'2026-09-19',cardId:21,cardTitle:'Intake',noteType:'general'}],total:1};
else if(url.pathname.endsWith('/chat-messages')||url.pathname.endsWith('/messages'))body={messages:[{id:Number(url.searchParams.get('offset'))+1,actorDisplayName:'Thomas Jansen',message:'The drawings are ready.',timestamp:1789800000}],hasMore:!Number(url.searchParams.get('offset')),nextOffset:1};
else if(url.pathname.endsWith('/direct-chats/thomas'))body={talkUrl:'/talk/thomas',otherUser:{id:'thomas'}};
else if(req.method==='POST'&&url.pathname.endsWith('/notes')){let raw='';for await(const chunk of req)raw+=chunk;body={id:100,...JSON.parse(raw),userId:'emma',updatedAt:'2026-09-19'};notes.unshift(body)}
else if(req.method==='PUT'&&/\/notes\/\d+$/.test(url.pathname)){let raw='';for await(const chunk of req)raw+=chunk;body=notes.find(n=>n.id===Number(url.pathname.split('/').pop()));Object.assign(body,JSON.parse(raw))}
else if(req.method==='DELETE'){notes=notes.filter(n=>n.id!==Number(url.pathname.split('/').pop()));body={deleted:true}}
if(body!==undefined){res.setHeader('Content-Type','application/json');res.end(JSON.stringify(body));return}
const path='/check/dist'+(url.pathname==='/'?'/index.html':url.pathname);if(fs.existsSync(path)){res.setHeader('Content-Type',path.endsWith('.js')?'text/javascript':path.endsWith('.css')?'text/css':'text/html');res.end(fs.readFileSync(path));return}res.statusCode=404;res.end('{}');});
(async()=>{await new Promise(r=>server.listen(8134,r));const browser=await chromium.launch({headless:true,executablePath:'/root/.cache/ms-playwright/chromium-1243/chrome-linux64/chrome',args:['--no-sandbox']});try{const page=await browser.newPage({viewport:{width:1440,height:1000}});const errors=[];page.on('pageerror',e=>{errors.push(e.message);console.log('ERROR',e.message)});page.on('console',m=>{if(m.type()==='error')console.log('CONSOLE',m.text())});await page.goto('http://localhost:8134');const css='/app/src/new/notes-theme.css';if(fs.existsSync(css))await page.addStyleTag({content:fs.readFileSync(css,'utf8')});await page.locator('.project-notes-list__note-card').first().waitFor();
await page.setViewportSize({width:390,height:844});await page.mouse.move(0,0);
await page.waitForTimeout(300);
assert.equal(await page.locator('.project-notes-list__note-actions').first().evaluate(el=>getComputedStyle(el).opacity),'1','Delete actions must remain visible without hover on touch screens');
assert(await page.evaluate(()=>document.documentElement.scrollWidth<=390),'Notes must fit a mobile viewport');
await page.screenshot({path:'/check/mobile.png',fullPage:true});await page.setViewportSize({width:1440,height:1000});await page.screenshot({path:'/check/desktop.png',fullPage:true});
await page.getByRole('button',{name:'Next',exact:true}).click();await page.waitForFunction(()=>document.querySelectorAll('.project-notes-list__note-card').length===1);
await page.locator('.project-notes-list__type-filter select').selectOption('decision');await page.waitForFunction(()=>document.querySelectorAll('.project-notes-list__note-card').length===6);
await page.getByRole('button',{name:'Private',exact:true}).click();await page.getByText('No private notes yet',{exact:true}).waitFor();
await page.getByRole('button',{name:'Add note',exact:true}).click();await page.getByPlaceholder('Enter note title...').fill('Private inspection questions');await page.locator('.tiptap').fill('Confirm the inspection time.');await page.screenshot({path:'/check/editor.png',fullPage:true});await page.getByRole('button',{name:'Create Note',exact:true}).click();await page.locator('.create-note-modal').waitFor({state:'hidden'});
await page.locator('.project-notes-list__type-filter select').selectOption('');await page.getByText('Private inspection questions',{exact:true}).click();await page.locator('input[placeholder="Enter note title..."]:visible').fill('Updated private questions');await page.getByRole('button',{name:'Save Changes',exact:true}).click();await page.locator('.create-note-modal:visible').waitFor({state:'hidden'});await page.getByText('Updated private questions',{exact:true}).waitFor();
page.on('dialog',d=>d.accept());await page.getByRole('button',{name:'Delete',exact:true}).click();await page.getByText('No private notes yet',{exact:true}).waitFor();
await page.getByRole('button',{name:'Card Notes',exact:true}).click();await page.getByRole('button',{name:'Comments',exact:true}).click();await page.getByText('Please review the drawings.',{exact:true}).waitFor();
await page.getByRole('button',{name:'Chat',exact:true}).click();await page.getByRole('button',{name:'Load older messages',exact:true}).click();await page.waitForFunction(()=>document.querySelectorAll('.project-notes-list__chat-message').length===2);
await page.getByRole('button',{name:/Direct Chats/}).click();await page.locator('.project-notes-list__direct-message-list').waitFor();await page.screenshot({path:'/check/chat.png',fullPage:true});await page.setViewportSize({width:390,height:844});await page.locator('.project-notes-list__back-btn--mobile-only').click();await page.getByPlaceholder('Filter members...').fill('Nobody');await page.locator('.project-notes-list__direct-sidebar-empty').waitFor();assert(await page.evaluate(()=>document.documentElement.scrollWidth<=390));assert.deepEqual(errors,[]);console.log('PASS: real Notes mobile actions/overflow, pagination, type/privacy filters, create/edit/delete with real rich editor, comments, chat pagination and mobile member navigation.');}finally{await browser.close();server.close()}})().catch(e=>{console.error(e);process.exitCode=1;server.close()});
